SELECT DISTINCT City, StateProvince FROM SalesLT.Address

SELECT TOP 10 PERCENT Name FROM SalesLT.Product ORDER BY Weight DESC

SELECT Name FROM SalesLT.Product ORDER BY Weight DESC OFFSET 10 ROWS
    FETCH NEXT 100 ROWS ONLY;
